### ISSUE TITLE
Build fails on MACOS

### ISSUE THREAD

**Issue by eurodata-uk** [aws-samples/saas-reference-architecture-ecs#15]
"This solution can be deployed via an [AWS Cloud9](https://aws.amazon.com/pm/cloud9/) environment on your AWS account, or directly from your laptop."

The build fails with 
"/build-application.sh 
user
ECR Repository 'user' does not exist. Creating...
{
  "repository": {
    "repositoryArn": "arn:aws:ecr:eu-west-1:381491906889:repository/user",
    "registryId": "381491906889",
    "repositoryName": "user",
    "repositoryUri": "[381491906889.dkr.ecr.eu-west-1.amazonaws.com/user](http://381491906889.dkr.ecr.eu-west-1.amazonaws.com/user)",
    "createdAt": "2024-07-11T15:34:07.688000+01:00",
    "imageTagMutability": "MUTABLE",
    "imageScanningConfiguration": {
      "scanOnPush": false
    },
    "encryptionConfiguration": {
      "encryptionType": "AES256"
    }
  }
}
Login Succeeded
[+] Building 1.2s (2/2) FINISHED                                                               docker:desktop-linux
 => [internal] load build definition from Dockerfile.user                                                          0.0s
 => => transferring dockerfile: 300B                                                                     0.0s
 => ERROR [internal] load metadata for public.ecr.aws/bitnami/node:20                                                    1.1s
------
 > [internal] load metadata for public.ecr.aws/bitnami/node:20:
------
Dockerfile.user:9
--------------------
  7 |   RUN yarn build user
  8 |
  9 | >>> FROM public.ecr.aws/bitnami/node:20
 10 |   WORKDIR /app
 11 |   COPY --from=build /app ./
--------------------
ERROR: failed to solve: public.ecr.aws/bitnami/node:20: no match for platform in manifest: not found"

This can be resolved by ensuring 
export DOCKER_DEFAULT_PLATFORM=linux/amd64

is set in the environment

**Comment by Hoseong-Seo** [comment]
Hi @eurodata-uk, thanks for your great interest,
I believe we already talked to being updated this.
I'm checking other OS, especially Cloud9' Linux and very newest environment macOS.
I don't think we use this reference would be tried on ARM environment.
Your opinion will be probably applied soon, unless any other confliction.
Because docker app is just sample, pre-set of docker environment provide a good test experience.

**Comment by Hoseong-Seo** [comment]
Thank you for your great interest, 
This is fixed.
