### ISSUE TITLE
CodeCommit is deprecated, and install script relies on codecommit

### ISSUE THREAD

**Issue by bschwarz** [aws-samples/saas-reference-architecture-ecs#18]
install.sh uses CodeCommit. However, CodeCommit has been deprecated, and no new repos can be added. Hence the script will fail.

**Comment by Hoseong-Seo** [comment]
Thank you for your great interest.
Yes, you're right, it was a sudden deprecation.
We've been trying to solve it.
Before that, If you have any account which already use the CodeCommit, you can do this refs in that account.

**Comment by Hoseong-Seo** [comment]
Thank you, this is fixed.
