### ISSUE TITLE
Install.sh fails on initial deployment 

### ISSUE THREAD

**Issue by jaydevn** [aws-samples/saas-reference-architecture-ecs#22]
I followed the README deployment steps on a cloud9 environment. However `install.sh <email>` fails as at L75 looking for existing ecs cluster `prod-cluster`
https://github.com/aws-samples/saas-reference-architecture-ecs/blob/main/scripts/install.sh#L75

This is a brand new deployment in a new region 

<img width="891" alt="Screenshot 2024-09-02 at 2 06 55 PM" src="https://github.com/user-attachments/assets/2615a789-0e90-4871-bde8-72adcd6ac750">

<img width="820" alt="Screenshot 2024-09-02 at 2 06 38 PM" src="https://github.com/user-attachments/assets/455ab2c5-bf2d-4733-af4d-1b8fbd7a67fb">

**Comment by Hoseong-Seo** [comment]
Accidentally, some workshop sources are in this reference.
I'll fix as soon as possible.

**Comment by Hoseong-Seo** [comment]
It's solved, thank you for your great interest & help.
